export * from './vdom';
import {
	VirtualNodeTagType,
  VirtualNodeType,
  VirtualDOMActionsType,
  VirtualDOMDiffType,
  ElementReplacerType,
  createTextNode,
  createCommentNode,
  createElement,
  isVirtualNode,
  createVirtualDOMFromSource,
  getVirtualDOM,
  getVirtualDOMDiff,
  getAttribute,
  setAttribute,
  removeAttribute,
  buildVirtualNodeWithRoutes,
  getComponentVirtualNodeById,
  mountVirtualDOM,
  transformTemplateStringToVirtualDOM,
} from './vdom';

export {
	VirtualNodeTagType,
  VirtualNodeType,
  VirtualDOMActionsType,
  VirtualDOMDiffType,
  ElementReplacerType,
  createTextNode,
  createCommentNode,
  createElement,
  isVirtualNode,
  createVirtualDOMFromSource,
  getVirtualDOM,
  getVirtualDOMDiff,
  getAttribute,
  setAttribute,
  removeAttribute,
  buildVirtualNodeWithRoutes,
  getComponentVirtualNodeById,
  mountVirtualDOM,
  transformTemplateStringToVirtualDOM,
}